name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 0,6,12 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SECTION_NAME: "waka"
          SHOW_COMMIT: "False"
